Set03| Add Node Documentation for...
DynamoDS/DynamoRevit pull request #3089
Opened 2024-08-28 18:11 UTC by johnpierson

### Purpose

Add node documentation for:
### "Element/ Family/Parameters Creation & Modification"
Parameter.GroupType
Parameter.ParameterByName
Parameter.SetValue
Parameter.SpecType
Parameter.StorageType
Parameter.Value

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers
@achintyabhat 

### FYIs
@Amoursol

2024-08-30 20:24 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Element.Faces.dyn
Suggest changing the view to to a different level as the example takes time to execute given there are 177 walls in L2. For example, I tried with Residential Lobby-South view, it's faster as there are not many walls (1/5th the execution time)

2024-08-30 20:26 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Element.Faces_img.jpg
Great example, hope the image could be better. Need to zoom in to see the node names. Also, using watch node for geometry would look better. Refer my example below-
![Screenshot 2024-08-30 131810](https://github.com/user-attachments/assets/a1eeb174-6716-46b1-add4-02817f897288)

2024-08-30 20:41 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Element.Solids.dyn
Similar to previous example, suggest changing the view to to a different level as the example takes a lil longer time to execute given there are 177 walls in L2. Works faster when I tried Residential Lobby-South view, it's faster as there are not many walls.

2024-08-30 20:42 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Element.Solids.md
Just wanted to say-Like the additional note on the nested list and Solid.ByUnion :)

2024-08-30 20:44 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Element.Solids_img.jpg
Again great example, but wish the image was better as I need to zoom in to see the node names. Maybe using Watch 3d node for geometry like below snippet
![Screenshot 2024-08-30 133946](https://github.com/user-attachments/assets/77999d5d-bf0a-4321-b7c6-2b1020c564dc)

2024-08-30 20:50 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.GroupType.md
> +For non-shared parameters parameter groups are predefined in Revit, while shared parameters allow for the definition of custom groups. For more information on working with shared parameters and group
Love the additional context! But, this statement is a little hard to read (especially for a non native english speaker). Suggest something like below so it reads better: "In Revit, parameter groups for non-shared parameters are predefined, whereas shared parameters allow you to define custom groups. For more information on working with shared parameters and groups, visit this help article: [Create Shared Parameter Files, Groups, and Parameters]

2024-08-30 20:54 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.ParameterByName.dyn
Do we really need the List.FirstItem node? 
![Screenshot 2024-08-30 135239](https://github.com/user-attachments/assets/d6d7dca8-9ced-4544-b5ae-bbe2473802f2)

2024-08-30 20:55 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.ParameterByName_img.jpg
Quick note, so we don't forget this-If the List.FirstItem node is removed from the example file, the image needs to be updated as well.

2024-08-30 21:00 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.SetValue.dyn
Do we really need the List.FirstItem node as there only one element in the list?

2024-08-30 21:01 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.SetValue_img.jpg
Quick note, so we don't forget this-If the List.FirstItem node is removed from the example file, the image needs to be updated as well.

2024-08-30 21:07 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.SpecType.dyn
Same here- not sure if and why List.FirstItem node is needed here. It might give the impression that the node will not work for a list of elements and the input needs to be single element.

2024-08-30 21:13 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.SpecType.md
> +These data types include:
There are more than the below listed spec types. So, to be clear suggest a minor modification as "These data type includes below (but are not limited to):Boolean,Int,String,e....etc"

2024-08-30 21:13 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.SpecType_img.jpg
Quick note, so we don't forget this-If the List.FirstItem node is removed from the example file, the image needs to be updated as well.

2024-08-30 21:16 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.StorageType.dyn
Same here- not sure if and why List.FirstItem node is needed here.

2024-08-30 21:16 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.StorageType_img.jpg
Quick note, so we don't forget this-If the List.FirstItem node is removed from the example file, the image needs to be updated as well.

2024-08-30 21:18 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.Value.dyn
Same here- not sure if and why List.FirstItem node is needed here.

2024-08-30 21:18 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.Value_img.jpg
Quick note, so we don't forget this-If the List.FirstItem node is removed from the example file, the image needs to be updated as well.

2024-08-30 21:25 UTC, achintyabhat requested changes
It might look like a lot of comments-but a generic theme in this set. You will see a recurring comment here. I wasn't quite sure why the First Item from the list is needed? Gives a wrong impression that the node cannot have a list of elements as input. Also, Two of the images are hard to read without zooming in. But other than that, as always thanks for the great examples and the notes for additional context where needed!

2024-09-03 18:25 UTC, johnpierson commented
Thanks so much @achintyabhat , I am not too sure why I had the first item node in there. lol 

All comments are addressed now!

2024-09-03 20:56 UTC, achintyabhat approved these changes
Thanks @johnpierson for the updates. This looks great!

2024-09-03 21:40 UTC, merged