Set06| Add Node Documentation for...
DynamoDS/DynamoRevit pull request #3093
Opened 2024-09-23 21:40 UTC by johnpierson

### Purpose
Add node documentation for:
View Disciplines
Visual Styles
ScheduleOnSheet.ScheduleView
Sheet.Schedules
View.AddFilter
View.FilterOverrides
View.GetCategoryOverrides
View.IsCategoryHidden
View.SetDiscipline
Visual Styles
View.SetFilterOverrides
ParameterFilterElement.ByRules

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers
@achintyabhat 

### FYIs
@Amoursol

2024-09-25 05:20 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.ScheduleOnSheet.ScheduleView.md
> +`ScheduleOnSheet.ScheduleView` returns the owner schedule view used to generate the instance on the sheet.
For readability and clarity, suggest rephrasing - "The ScheduleOnSheet.ScheduleView node in Dynamo for Revit is used to retrieve the original schedule view that was used to create the specific schedule instance on a sheet."

2024-09-25 05:25 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.ScheduleOnSheet.ScheduleView_img.jpg
Image is not very clear to read. Like how this example is giving additional tip with the filtering for revision schedules.  As this example is similar to Sheet.Schedules node, suggest keeping this example for the other node. Maybe keep this example crisp and focused on this node. Even something like this could work. 
![image](https://github.com/user-attachments/assets/68058c58-4231-4fe2-b72f-69b32ff139de)

2024-09-25 05:26 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.ScheduleOnSheet.ScheduleView.md
> +In the example below, the schedule instances are returned for the selected sheet. The revision schedules are then filtered out with `List.FilterByBoolMask`. Additionally, the owner view for the sched
If the example is changed, note to update this section of the In Depth description.

2024-09-25 05:38 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.AddFilter.md
> +
This sentence has too many "Views" and my brain can't handle (lol).  Maybe rephrase as "View.AddFilter adds the specified filter to the given view. If the view has a view template applied, this node will add the filter to it's view template."

2024-09-25 05:42 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.AddFilter.md
Love the example for this node!!!

2024-09-25 05:50 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.FilterOverrides.md
> +In the example below, the view filters are collected from the current view and the filter overrides are returned.
Note to update the example description to align with example file and image

2024-09-25 05:50 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.FilterOverrides_img.jpg
Note to update image of the updated dyn file.

2024-09-25 05:53 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.GetCategoryOverrides.dyn
Depending on user's active view, this might return just empty lists- might be confusing for new users. 
![image](https://github.com/user-attachments/assets/0fa6a5e4-c81b-4523-b759-c33517cea085)

2024-09-25 06:03 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.FilterOverrides.dyn
Depending on user's active view, this might return just empty lists- might be confusing for new users. 
![image](https://github.com/user-attachments/assets/0fa6a5e4-c81b-4523-b759-c33517cea085)

2024-09-25 06:07 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.GetCategoryOverrides.dyn
Maybe it is just me. Document.ActiveView node is throwing an error for me. I am in the same project and view, other examples with the same node work fine!! Will ask someone else to try as well.
![Screenshot 2024-09-24 225929](https://github.com/user-attachments/assets/cb253e55-be55-486c-a956-788ba83cea59)

2024-09-25 06:10 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.IsCategoryHidden.md
> +In the example below, the active view's view template from the current document is retrieved. `View.IsCategoryHidden` reports if the wall category is hidden.
For readability, suggest rephrasing this as "In the example below, the view template of the active view from the current document is retrieved...." Sorry for being picky! Active view's view template is a hard to read.

2024-09-25 06:19 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.AddFilter.dyn
Note to update the dyn file in alignment with the comment below.

2024-09-25 06:19 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.AddFilter_img.jpg
Note to update the image file ito align with the comment above.

2024-09-25 06:25 UTC, achintyabhat requested changes
Thanks John for all the amazing examples on this set, very handy for users! Just some minor comments on the description for better readability. Also suggest splitting some of the examples into smaller chunks , instead of repeating the example file for multiple nodes.

2024-09-25 18:05 UTC, johnpierson commented
I believe all comments are now addressed @achintyabhat ! Thanks for that! All made sense to me and improved the readability for sure.

2024-09-26 04:57 UTC, achintyabhat approved these changes
Thanks @johnpierson for all the changes. Looks great!

2024-09-26 17:57 UTC, merged