Set07| Add Node Documentation for...
DynamoDS/DynamoRevit pull request #3096
Opened 2024-10-01 18:06 UTC by johnpierson

### Purpose
ModelText.Depth
ModelText.Position
ModelText.Text
Viewport.BoxCenter
Viewport.BoxOutline
Viewport.LabelLineLength
Viewport.LabelOffset
Viewport.LabelOutline
Viewport.SetLabelLineLength
Viewport.Sheet
Viewport.View

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers
@achintyabhat 

### FYIs
@Amoursol

2024-10-02 18:18 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.ModelText.Depth.md
Retrieved Depth is in what units?

2024-10-02 18:22 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Viewport.LabelLineLength.md
> +In the example below, all of the viewports from the selected sheet are collected and the line lengths are reported.
For clarity, can be rephrased as "In the example below, all of the viewports from the selected sheet are collected and the lengths of the viewport label lines are retrieved."

2024-10-02 18:27 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Viewport.LabelOutline_img.jpg
The 3D Watch node is not very clear. 
![Revit Elements Viewport LabelOutline](https://github.com/user-attachments/assets/e02acc99-bf46-464d-ac90-383a852620cf)

2024-10-02 18:32 UTC, achintyabhat requested changes
This set is almost good to go, just two minor comments.

2024-10-02 22:23 UTC, johnpierson commented
Sweet. All changes are made. And node samples moved from review.

2024-10-03 01:26 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/Revit.Elements.Viewport.LabelLineLength.md
> +n the example below, all of the viewports from the selected sheet are collected and the lengths of the viewport label lines are retrieved.
I is missing in the "In".

2024-10-03 14:02 UTC, achintyabhat approved these changes

2024-10-03 19:44 UTC, merged