Set08| Add Node Documentation for...(Documentation Added: 20 nodes)
DynamoDS/DynamoRevit pull request #3098
Opened 2024-10-03 19:45 UTC by johnpierson

### Purpose

### Declarations

Detail Level
Select UV on Face
FamilyParameter.CanAssignFormula
FamilyParameter.Id
FamilyParameter.IsReadOnly
FamilyParameter.IsReporting
FamilyParameter.IsShared
FamilyParameter.Name
FamilyParameter.Unit
GlobalParameter.ByName
GlobalParameter.FindByName
GlobalParameter.Name
GlobalParameter.SetValue
GlobalParameter.Value
GlobalParameter.Visible
Parameter.CreateSharedParameter
Parameter.CreateSharedParameterForAllCategories
Parameter.SharedParameterFile
  
Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers
@achintyabhat 

### FYIs
@Amoursol

2024-10-08 22:35 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/DSRevitNodesUI.DetailLevel.md
> +Available detail levels available include:
Available in this sentence is repetitive. Maybe rephrase as "Detail levels available include:"

2024-10-08 23:12 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.FamilyParameter.Id.md
> +In the example below, the current Revit document (a door family from the sample model) is open. The parameters in the family are returned, along with the element id as an integer. note, built-In Revi
Change "note, built-In Revit parameters have a negative (-) prefix." to "Note:  Built-In Revit parameters have a negative (-) prefix."

2024-10-08 23:27 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.GlobalParameter.GroupType.md
> +`GlobalParameter.GroupType` returns the group type for the given parameter. Information regarding group types can be found in the documentation located, [here](https://help.autodesk.com/view/RVT/2025
Is this documentation link accurate? Not sure how Unit types are relevant here.

2024-10-08 23:36 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Parameter.CreateSharedParameter.md
> +`Parameter.CreateSharedParameterForAllCategories` will add a parameter with the given values to the given categories in the current Revit document.
Isn't the node name just "Parameter.CreateSharedParameter"?

2024-10-08 23:42 UTC, achintyabhat requested changes
This set looks good and is almost good to go! A couple of minor comments that needs to be addressed.

2024-10-09 16:05 UTC, johnpierson commented
Awesome. All comments fixed.

2024-10-09 17:36 UTC, achintyabhat approved these changes
Thanks for all making all the changes. Looks great!

2024-10-09 18:03 UTC, merged