Set010| Add Node Documentation for...(Documentation Added: 31 nodes)
DynamoDS/DynamoRevit pull request #3101
Opened 2024-10-08 18:45 UTC by johnpierson

### Purpose

### Declarations

DSRevitNodesUI.ViewDuplicateOptions.dyn
Revit.Elements.Element.GetJoinedElements.dyn
Revit.Elements.Element.UnjoinAllGeometry.dyn
Revit.Elements.Element.UnjoinGeometry.dyn
Revit.Elements.ElementType.CanBeCopied.dyn
Revit.Elements.ElementType.CanBeDeleted.dyn
Revit.Elements.ElementType.Duplicate.dyn
Revit.Elements.ElementType.FamilyName.dyn
Revit.Elements.ElementType.Name.dyn
Revit.Elements.FamilyInstance.Space.dyn
Revit.Elements.Space.Area.dyn
Revit.Elements.Space.CenterBoundary.dyn
Revit.Elements.Space.CoreBoundary.dyn
Revit.Elements.Space.CoreCenterBoundary.dyn
Revit.Elements.Space.FinishBoundary.dyn
Revit.Elements.Space.Height.dyn
Revit.Elements.Space.IsPointInsideSpace.dyn
Revit.Elements.Space.Location.dyn
Revit.Elements.Space.Name.dyn
Revit.Elements.Space.Number.dyn
Revit.Elements.Space.SetName.dyn
Revit.Elements.Space.SetNumber.dyn
Revit.Elements.Space.Volume.dyn
Revit.Elements.Views.View.ExportAsImage.dyn
Revit.Elements.Views.View.SetCropBoxVisible.dyn
Revit.Elements.Wall.ByCurveAndHeight.dyn
Revit.Elements.WallType.ByName.dyn
Revit.Elements.WallType.Function.dyn
Revit.Elements.WallType.GetThermalProperties.dyn
Revit.Elements.WallType.Name.dyn
Revit.Elements.WallType.Width.dyn
  
Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers
@achintyabhat 

### FYIs
@Amoursol

2024-10-09 18:44 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/DSRevitNodesUI.ViewDuplicateOptions.md
> +In the example below, the detail view "North Wall Window Detail" is duplicated with a prefix of "-Revision 1" with detailing.
The node in the example is View.DuplicateView. But the description and file name is for View Duplicate Options. Looks like its been mixed up?

2024-10-09 18:44 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/DSRevitNodesUI.ViewDuplicateOptions_img.jpg
Note to update the image if needed based on the above comment or rename the image.

2024-10-14 03:01 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.ElementType.Duplicate.md
> +`ElementType.Duplicate` attempts to duplicate the given element with the given name. If the name is already taken an error will be presented on the node.
"type" is missing here-attempts to duplicate the given element "type" with the given name

2024-10-14 03:11 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Space.IsPointInsideSpace.md
Thanks for highlighting a good use case here with the example :)

2024-10-14 03:27 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.ExportAsImage.dyn
Got a warning in my case as I do not have a pictures folder in this location. It might confuse a novice naive user. Rather suggest, keeping a file path as an input and concatenating with the view name to that path to create the final path.

2024-10-14 03:28 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.ExportAsImage.md
Note to update description as needed if the dyn file is updated.

2024-10-14 03:28 UTC, achintyabhat commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.ExportAsImage_img.jpg
Note to update image as needed if the dyn file is updated.

2024-10-14 03:29 UTC, achintyabhat requested changes
This set looks good! Just one minor typo and one of the example needs modification. Then we should be good to go.

2025-01-02 17:59 UTC, achintyabhat commented
@johnpierson Just noticed that this was never updated and merged. It required some minor updates. Can you please make the changes?

2025-01-02 20:02 UTC, johnpierson commented on doc/distrib/NodeHelpFiles/_review/Revit.Elements.Views.View.ExportAsImage.dyn
changed it to desktop. maybe that will work?

2025-01-02 20:53 UTC, achintyabhat approved these changes

2025-01-03 19:43 UTC, merged